name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  django-ci-test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      LOCAL_DB_NAME: ${{ env.POSTGRES_DB }}
      LOCAL_DB_USER: ${{ env.POSTGRES_USER }}
      LOCAL_DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
      LOCAL_DB_HOST: localhost

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd django_blog
        coverage run manage.py test
        coverage report
